# This file was generated by GoReleaser. DO NOT EDIT.
cask "fugaro" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "00502d35fa19bdb8683758d536ebce4d4ead2c931d58bfa0a548b013c0e61a9e"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1d15408e03e72b71842e402a69b3fcf73a49424374f2ff10231988f985ccd74"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b7203c1f615f622677633621a767c2c1aa5714cbd16a4575e364e6afe0e37aaa"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31df9e41b4cb82d2ab87557176b857781fd799d5e8a7279f4e610c680d449940"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fugaro"
  desc "Fleeting cloud workers that run coding-agent tasks and always end with a pull request"
  homepage "https://github.com/dimipaun/fugaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fugaro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fugaro"]
    end
  end

  # No zap stanza required
end
