# This file was generated by GoReleaser. DO NOT EDIT.
cask "fugaro" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "ceb0bbce9ed2acd9f5d2d6c1cb788ae18dc32d0ca27b2cbcf31cddfcd5a09304"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38dd59715186c3203067de63a33e6dcffd7e47f024b9cb34966d8668fd5cafed"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3899cbcc4ad50086010a30bc4394eb7da6d3e4c32945fbb287dcb3b345c943d"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "abe889140da33a84689e07b31ce3a58666c7c53594e44ca70dd872ad8cee21c5"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fugaro"
  desc "Fleeting cloud workers that run coding-agent tasks and always end with a pull request"
  homepage "https://github.com/dimipaun/fugaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fugaro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fugaro"]
    end
  end

  # No zap stanza required
end
