# This file was generated by GoReleaser. DO NOT EDIT.
cask "fugaro" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "fdf1ec5a89000ef85173551b95df620ad6d211dbe68b5fbe700867fc1df975c7"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d750b9c3abbc23d86a491b710399405cc881d62f6d001887e426e9aca8ae29d"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25889cd04f5c889fc388f9c45d51661b3200d6e41710ef5b1d63a8373b6d698f"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a64733a3051354531e8dc2a5cd5bfe7c281e9db361f9f6051f2dcf542668fef4"
      url "https://github.com/dimipaun/fugaro/releases/download/v#{version}/fugaro_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fugaro"
  desc "Fleeting cloud workers that run coding-agent tasks and always end with a pull request"
  homepage "https://github.com/dimipaun/fugaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fugaro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fugaro"]
    end
  end

  # No zap stanza required
end
